#!/bin/sh
set -eux

for dir in ./* ; do
    if [[ -d "$dir" ]]; then
        echo "processing $dir"
        cd $dir
        composer ${COMMAND} --ignore-platform-reqs --no-scripts
        cd ../
    fi
done
